source "https://rubygems.org"
gem 'github-pages'
gem "type-on-strap"
gem "jekyll-redirect-from"
gem "jekyll-paginate"
gem "jekyll-seo-tag"
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "jekyll-last-modified-at"
gem "webrick", "~> 1.8"
