name: Sync multiple branches
on:
  push:
    branches:
      - '*'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge pages -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: gh-pages
          target_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
